// RUN: mulberry-opt --lower-mulberry %s | FileCheck %s

module {
  func.func @alloc_scalar() -> !mulberry_core.ptr<i64> {
    %count = arith.constant 1 : i64
    %ptr = mulberry_core.heap.alloc i64, %count : !mulberry_core.ptr<i64>
    return %ptr : !mulberry_core.ptr<i64>
  }

  func.func @alloc_record(%count: i64)
      -> !mulberry_core.ptr<!mulberry_core.record<Person {age: i64, active: i1}>> {
    %ptr = mulberry_core.heap.alloc !mulberry_core.record<Person {age: i64, active: i1}>, %count
        : !mulberry_core.ptr<!mulberry_core.record<Person {age: i64, active: i1}>>
    return %ptr : !mulberry_core.ptr<!mulberry_core.record<Person {age: i64, active: i1}>>
  }
}

// CHECK-DAG: llvm.func @mulberry_boehm_malloc(i64) -> !llvm.ptr
// CHECK-LABEL: func.func @alloc_scalar() -> !llvm.ptr
// CHECK: %[[I64_COUNT:.*]] = arith.constant 1 : i64
// CHECK: %[[I64_NULL:.*]] = llvm.mlir.zero : !llvm.ptr
// CHECK: %[[I64_NEXT:.*]] = llvm.getelementptr %[[I64_NULL]][1] : (!llvm.ptr) -> !llvm.ptr, i64
// CHECK: %[[I64_SIZE:.*]] = llvm.ptrtoint %[[I64_NEXT]] : !llvm.ptr to i64
// CHECK: %[[I64_BYTES:.*]] = arith.muli %[[I64_SIZE]], %[[I64_COUNT]] : i64
// CHECK: %[[I64_PTR:.*]] = llvm.call @mulberry_boehm_malloc(%[[I64_BYTES]]) : (i64) -> !llvm.ptr
// CHECK: return %[[I64_PTR]] : !llvm.ptr

// CHECK-LABEL: func.func @alloc_record(
// CHECK-SAME: %[[COUNT:.*]]: i64) -> !llvm.ptr
// CHECK: %[[REC_NULL:.*]] = llvm.mlir.zero : !llvm.ptr
// CHECK: %[[REC_NEXT:.*]] = llvm.getelementptr %[[REC_NULL]][1] : (!llvm.ptr) -> !llvm.ptr, !llvm.struct<(i64, i1)>
// CHECK: %[[REC_SIZE:.*]] = llvm.ptrtoint %[[REC_NEXT]] : !llvm.ptr to i64
// CHECK: %[[REC_BYTES:.*]] = arith.muli %[[REC_SIZE]], %[[COUNT]] : i64
// CHECK: %[[REC_PTR:.*]] = llvm.call @mulberry_boehm_malloc(%[[REC_BYTES]]) : (i64) -> !llvm.ptr
// CHECK: return %[[REC_PTR]] : !llvm.ptr
// CHECK-NOT: mulberry.
